### ISSUE TITLE
не работает яху

### ISSUE THREAD

**Issue by kocunop** [stleon/OmgSite#9]
похоже страничка выдачи Яху парсится криво.  

Traceback (most recent call last):
  File "site_auditor.py", line 374, in <module>
    print(SiteAuditor(input('Enter site, please: '), input('Full scan? y/n/2w ')))
  File "site_auditor.py", line 38, in __init__
    self.info_green()
  File "site_auditor.py", line 60, in info_green
    self.pro_index = self.index()
  File "site_auditor.py", line 279, in index
    yahoo = int(yahoo)
ValueError: invalid literal for int() with base 10: '&nbsp;&raquo;</span></a></li><script> var s = false tsre2sdtsv2= null cookies = "; " + document.cookie dss = cookies.split("; DSS=") m ua = window.navigator.userAgent.toLowerCase(); m = ua.match(/fir

**Comment by stleon** [comment]
Спасибо за участие, в данный момент не могу ошибку исправить, и как мне кажется, там не только яху отвалился, времени много прошло
